### ISSUE TITLE
Help with messaging about file formats

### ISSUE THREAD

**Issue by binx** [mapzen/data-pages#112]
Please help us write up better descriptions of what each format is, and how to use it!

Also it would be great to have some info about the four different file formats that come though in the shapefile zip... people don't know what they mean!

**Comment by souperneon** [comment]
Discussed with @rmglennon and Katie as improvement to documentation.

**Comment by rmglennon** [comment]
closing with new docs, including a separate topic just on file formats! 

fixed here by @kkowalsky in https://github.com/mapzen/data-pages/pull/237
