### ISSUE TITLE
Provide ops with a place to download cities.json

### ISSUE THREAD

**Issue by migurski** [mapzen/data-pages#124]
Should match https://github.com/mapzen/metroextractor-cities/blob/master/cities.json in layout, and be useable by @heffergm in `metroextractor-cities` code.

**Comment by heffergm** [comment]
Just FYI, I've been pulling the git repo to get the data. If you want to make it an endpoint that's fine, but I can just as easily continue to pull the repo.

**Comment by migurski** [comment]
I’m making an endpoint, it’s pretty easy to do.
