### ISSUE TITLE
show custom extracts made by other users?

### ISSUE THREAD

**Issue by burritojustice** [mapzen/data-pages#134]
If a users is searching for San Francisco, will we ever show extracts that other users have created?

https://mapzen.com/data/metro-extracts-alt/odes/extracts/6ec805a0d6af

**Comment by binx** [comment]
my understanding is no, that we want to restrict people to only seeing the top 200, and their requested extracts

**Comment by migurski** [comment]
That’s my understanding as well.

**Comment by binx** [comment]
closing this because it is not scoped for the next release, and moving to gdocs
