### ISSUE TITLE
Create a new page when user selects a place from the dropdown

### ISSUE THREAD

**Issue by souperneon** [mapzen/data-pages#138]
Let's make this behavior the same as clicking on an existing extract with a breadcrumb to go back. This will clear some of the confusion some users had with the search bar behavior and make it more consistent

**Comment by migurski** [comment]
This seems odd to me, since the drop-down is an autocomplete. Can you say more about how this will work, particularly in concert with the comps you shared yesterday?

**Comment by souperneon** [comment]
the flow I shared yesterday, is on the back burner for now (right?)

In the current flow, clicking on an item in the list takes you to a downloads page. Users used the breadcrumb or browser back to get back
When users picked a result from the dropdown it showed a blue box on the left that they could start messing with for custom extracts, but that had them in a state where they were still on the landing page and the URL hadn't changed and they had no idea how to "go back" to the map reset to the world, search cleared and with the list of existing extracts (they tried to look for breadcrumb and it wasn't there). 

If we are saying you can have an extract for anywhere, we can try making this page look different from the landing and users can easily go back if they were just clicking around out of curiosity. It also then starts and finishes on the same page template after they login and return to the same page with the message "sit tight…" and then also the email brings them back
They can also share the URL to show others, Hey look! I can make an extract for my small town in North Dakota (not sure why i picked ND, it never comes up :P)

**Comment by migurski** [comment]
Yes, back burner—thanks for clarifying. It was hard to tell if this issue was something you wanted to talk about immediately or not. I will come up with a milestone to reflect work after the next round of testing.

**Comment by souperneon** [comment]
@migurski I was hoping we can try that before the release tomorrow because it's something we found in the last round.

**Comment by souperneon** [comment]
Closing in favor of making the 'x' do a rest of the UI and map view to show the full world.
