### ISSUE TITLE
Connect sites for launch

### ISSUE THREAD

**Issue by binx** [mapzen/data-pages#139]
@migurski the plan is to launch the new on at -alt/ and keep the old one at the same address, correct? The blog post will be the only place on the site with the -alt/ link, correct?

@burritojustice ^ another copy thing I would love help with, maybe "<< If you'd like to use the old site, click here"

**Comment by migurski** [comment]
I should say something about the 200 in the blog post, I think.

**Comment by binx** [comment]
* [ ] top: add link to old site and request for feedback
* [ ] old: add link to new site and request for feedback
* [ ] all: add feedback email requests

**Comment by souperneon** [comment]
After discussion, add a banner above pages on both /metro-extracts and /metro-extracts-alt linking to a Google survey form (http://goo.gl/forms/OIEdDWr7RIC04oqo2)
Repurpose the existing yellow box and change copy:
Try the updated Metro Extracts!
We are excited to open up a new feature: your own custom extracts. Search and get an extract for anywhere in the world within an hour! You're going to love it :)
SURE, I'LL TRY IT!
