### ISSUE TITLE
What's the best information hierarchy for the downloads page?

### ISSUE THREAD

**Issue by burritojustice** [mapzen/data-pages#160]
good to have the geojson border on the page, but probably best to put below the metro extracts

![image](https://cloud.githubusercontent.com/assets/3979711/16850358/9021e07e-49b3-11e6-82ab-a81fbcf46c99.png)

**Comment by binx** [comment]
It's at the top because that's the only place that people noticed it on the page :/ and when they did see it they responded positively...

We could work on making a more compact layout... although I think one of the appealing things of this page was having a long page to put all possible links on

**Comment by migurski** [comment]
Maybe it could be grouped with the other downloads?

**Comment by migurski** [comment]
Anyway, let's file this one for testing and not jump to a solution.

**Comment by souperneon** [comment]
Here's a wireframe taking into account the feedback we have so far and drawing inspiration from HOT OSM.

![metroextracts_ui_3 1](https://cloud.githubusercontent.com/assets/6125224/17303285/fd2b104e-57ed-11e6-9fe6-fc052f4dc371.png)
![metroextracts_ui_3 2](https://cloud.githubusercontent.com/assets/6125224/17303284/fd295b32-57ed-11e6-8079-8e1edfe54193.png)

- Added some status information
- Made the "sit tight" and timing message more prominent
- Added OSM data license info. We haven't had this but maybe it's necessary?
- Moved clipping area as one of the options in the download
* Still working on adding links for docs, tutorial etc.

**Comment by souperneon** [comment]
@binx we had a user write in to support after creating 3 extracts and not being able to find them. Maybe adding a link to the "sit tight…" message that says, "Go here to look at all your custom extracts and their status"

**Comment by binx** [comment]
![screen shot 2016-08-03 at 1 21 08 pm](https://cloud.githubusercontent.com/assets/589151/17380744/73907eb4-597d-11e6-8400-48963816782a.png)
![screen shot 2016-08-03 at 1 22 42 pm](https://cloud.githubusercontent.com/assets/589151/17380745/739206a8-597d-11e6-9205-5ecea67ac00b.png)

**Comment by souperneon** [comment]
This looks good! Should we make the "to clip this extract…" bold as well?
