### ISSUE TITLE
Minor tweaks for Metro Extracts Alt version

### ISSUE THREAD

**Issue by souperneon** [mapzen/data-pages#162]
- [x] Styling for the link of encompassing extract to make it stand out a bit more
![screen shot 2016-07-14 at 2 28 48 pm](https://cloud.githubusercontent.com/assets/6125224/16850947/5480a2b4-49cf-11e6-8f09-0a566493fbcb.png)

- [x] Button text copy for custom extract creation
GET CUSTOM EXTRACT or GET {requested-extract-name} EXTRACT

- [x] Could we try to make just the format name a link 
![screen shot 2016-07-14 at 2 32 17 pm](https://cloud.githubusercontent.com/assets/6125224/16851064/d44f9f18-49cf-11e6-8460-c06f26970d3e.png)

- [x] Update the copy for - Large Request (> 1deg) 
Copy:
Hey, looks like we don’t have an extract for {autocomplete-selection} ready to download.
But you can make your own!
Drag the corners of the blue box on the map to define your custom extract.
[GET CUSTOM EXTRACT]
_(Note: You have defined a large area as a custom extract. This might take a few hours to finish. You will be guided to sign in or sign up for a free Mapzen Developer account to complete this request)_

- [x] Update the copy for -Too Large (> 5deg)
Copy:
Hey, looks like we don’t have an extract for {autocomplete-selection} ready to download.
But you can make your own!
Drag the corners of the blue box on the map to define your custom extract.
_(same red bg error color as it is now)_
Sorry, the area you have defined is too large. Drag the corners of the blue box on the map to make it smaller.

- [x] Add 'x' in search bar as soon as user starts typing
- [x] Replace 'About' section with new copy

**More from Mapzen**
Read more about Metro Extracts in [this blog post](https://mapzen.com/blog/metro-extracts-on-demand/)

The Mapzen [Vector Tile Service](https://mapzen.com/projects/vector-tiles/) provides worldwide basemap coverage sourced from OpenStreetMap and other open data projects, updated daily!
Get started with your free [Mapzen Developer account](https://mapzen.com/developers).

**Comment by binx** [comment]
btw the copy has already been updated for the 1 and 5 deg

**Comment by binx** [comment]
I also disagree about making the encompassing extract link blue, since it's an existing/popular extract and we've been reserving red for that. I think it should either be red or stay black like it is right now. I'm happy to bold the title though

**Comment by souperneon** [comment]
gotcha, yeah bolding the title and the link? It's tricky coz it turns red on hover but doesn't otherwise look like a link :/

**Comment by souperneon** [comment]
copy is still showing up as the old copy for me for 1 and 5 deg (i hard refreshed a couple of times)
![screen shot 2016-07-14 at 2 47 53 pm](https://cloud.githubusercontent.com/assets/6125224/16851517/fe9e4092-49d1-11e6-8afb-31e6130ece94.png)

**Comment by binx** [comment]
that's what's listed on the doc in blue under >5deg... maybe paste in here what you would like me to change it to?
