### ISSUE TITLE
How do we handle places that aren't in search?

### ISSUE THREAD

**Issue by binx** [mapzen/data-pages#183]
Do we have people email us? Email search? WOF?

**Comment by migurski** [comment]
Needs @dianashk and @straup input.

**Comment by sleepylemur** [comment]
Just my 2 cents, but having a zoomed out map and scrolling/zooming to the location and then drawing a box seems like a reasonable solution to me.
When I did user testing I looked for that behavior assuming it was possible.
I realize it'd be non-trivial to make that integrate nicely with the current app.

**Comment by dianashk** [comment]
It would be great if there was a way for a user to say what I searched for isn't there so I'm going to make a custom box and give it a custom name. Then behind the scenes an email could go out to search@mapzen.com with what they searched for and didn't find, as well as the bbox and custom name they ended up using for their extract. Then we can evaluate those on a case by case basis. Does that sound reasonable?

**Comment by migurski** [comment]
We are going to provide this information for admin users via a recent-downloads linked, see also https://github.com/mapzen/data-pages/pull/177.
