### ISSUE TITLE
Add download size information to the metro and extract pages

### ISSUE THREAD

**Issue by binx** [mapzen/data-pages#184]

**Comment by migurski** [comment]
@sleepylemur is there something we can do in ODES API here, or should I issue and cache an HTTP HEAD request against each file?

**Comment by sleepylemur** [comment]
the backend would have to query for each file as well... wherever seems like a sensible place to do it is fine with me.

**Comment by migurski** [comment]
Okay, I’ll have our end do the querying, since it’s needed for display purposes.
