### ISSUE TITLE
Add API call to regenerated requested extracts

### ISSUE THREAD

**Issue by binx** [mapzen/data-pages#194]
Scenario: Someone wants Fremont data, but they want to be able to update it without having to go through the request flow again. Should we allow an "update" button, such as on /odes/extracts?

@migurski @sleepylemur would love input on this

**Comment by migurski** [comment]
I think this is a great idea. It should probably come with some indication of when an extracts was requested, so a user understands why it needs to be re-requested.

**Comment by souperneon** [comment]
Agreed. We should maintain the date we have right now. 
HOT OSM has this:
![screen shot 2016-07-29 at 3 44 57 pm](https://cloud.githubusercontent.com/assets/6125224/17261379/72f2297c-55a3-11e6-840d-4bc87dd05748.png)

They use "Rerun export" and in the user dashboard under "My exports" have the ability to manage an export i.e. delete or rerun.

**Comment by migurski** [comment]
This can happen after https://github.com/mapzen/data-pages/pull/193 is complete.
