### ISSUE TITLE
Improve copy on auth page for Metro Extracts

### ISSUE THREAD

**Issue by souperneon** [mapzen/data-pages#216]
@migurski would love your input on this
Current copy: "To use Metro Extracts and other Mapzen services, get your API key"
It can be misleading making users think they need a key.

Proposed copy: "Create a Mapzen Developer account to finish creating your custom Metro Extract and get API keys for other Mapzen services"
This can help (if anyone reads) to clarify the confusion some users have expressed around custom Metro Extracts account and Mapzen Developer account being the same.

![screen shot 2016-08-03 at 10 55 30 am](https://cloud.githubusercontent.com/assets/6125224/17370420/0000316e-596a-11e6-981b-fcfd1da0019c.png)

**Comment by migurski** [comment]
This page live in `/developers` though, so the changes would have to happen there.

**Comment by souperneon** [comment]
Ok. If copy looks good I'll close it here and open it there :) Already done that once today! lol

**Comment by migurski** [comment]
Heh, sure. The copy is definitely not controlled in this repo.

**Comment by souperneon** [comment]
Moved to the developer repo https://github.com/mapzen/developer/issues/815
