### ISSUE TITLE
Add language for how to request a custom extract

### ISSUE THREAD

**Issue by binx** [mapzen/data-pages#218]
right now you have to start interacting with the page to find this information, let's add a sentence explaining how to do this

**Comment by souperneon** [comment]
How about…

Each week, Metro Extracts automatically creates snapshots of OpenStreetMap data into manageable, metro-area files in a variety of formats for you to use. Download an extract from the list of **popular extracts** below to get started right away.
Extracts last updated on: <date>

Can't find what you are looking for? You can get **custom extracts** of anywhere in the world! To get started, search for the place you are looking for.
