### ISSUE TITLE
Develop wireframes based on user research input

### ISSUE THREAD

**Issue by migurski** [mapzen/data-pages#22]
As user research draws to a close, iterate on wireframes for Extracts UI.

**Comment by souperneon** [comment]
@binx this is one of the layout options… working on another one

**Option 1**
![metroextracts_ui_1 1](https://cloud.githubusercontent.com/assets/6125224/16020081/4bc5cd1a-317a-11e6-90b7-2e3186f59a9d.png)
![metroextracts_ui_1 2](https://cloud.githubusercontent.com/assets/6125224/16020082/4bc5e7e6-317a-11e6-80fc-7f2440a20c89.png)

**Comment by migurski** [comment]
A few comments from a phone conversation with Rachel where we mentioned these:

* The Brisbane card is good, but it might work better to link out to a whole page of just Brisbane.
* The side-by-side layout is super interesting.
* The contents of the sidebar ("request an extract", etc.) could be spread throughout the page, closer to where they are needed. For example, suggest that a user request an extract when they search for something and it doesn't exist, or scroll to the bottom of the list.
* WoF + Search gives us the ability to match place searches that are included in another extracts, for example if a user searches for Fremont and we know that it’s contained within the bounds of the SF Bay Area. Many of the default extracts already contain generous surrounding countryside buffers.
