### ISSUE TITLE
Update top-text on old metro extracts page 

### ISSUE THREAD

**Issue by migurski** [mapzen/data-pages#236]
Master branch in this repo now creates this page: https://mapzen.com/data/metro-extracts-old/

We need to change or remove the top text there, to say that this is now the _old_ extracts.

**Comment by souperneon** [comment]
Welcome to the new and enhanced Metro Extracts! We have made creating custom extracts super easy. Give it a spin and send us [your feedback](mailto:hello@mapzen.com)!

Looking for the old version? You can see it [here](https://mapzen.com/data/metro-extracts-old/) for a short period of time.

**Comment by migurski** [comment]
It needs to say the opposite actually — we need text for the old version.

**Comment by souperneon** [comment]
😱  my bad.
Metro Extracts just got an upgrade! 
Try it [here](https://mapzen.com/data/metro-extracts/). We have made creating custom extracts super easy. Give it a spin and send us [your feedback](mailto:hello@mapzen.com)!

This old version with only be available for a short period of time.
