### ISSUE TITLE
Explore options for making a request

### ISSUE THREAD

**Issue by binx** [mapzen/data-pages#34]

**Comment by migurski** [comment]
Couple thoughts:

* Pre-position the box based on WoF search
* Use a standard buffer around WoF’s shape—5km? 20km?
* Maintain WoF ID someplace if the box doesn't get moved around too much

**Comment by binx** [comment]
currently using 20km offset
@migurski do you know if the WOF URL is always splitting the ID by 3/3/2? https://whosonfirst.mapzen.com/data/859/218/81/85921881.geojson

**Comment by migurski** [comment]
I’m not sure if the split is consistent, so you should use this URL form instead: `https://whosonfirst.mapzen.com/spelunker/id/{id}.geojson`. It will redirect for you.

**Comment by binx** [comment]
to view: https://mapzen-odes-extracts-pr-35.herokuapp.com/static/index.html
