### ISSUE TITLE
Error handling: reject extracts that are too large

### ISSUE THREAD

**Issue by binx** [mapzen/data-pages#62]
hard limit at 5x5, soft limit with warning on... uh... 1x1?

**Comment by migurski** [comment]
Extract should say "whoa that’s too big" at some useful part of the process. @sleepylemur, is there a practical upper limit on extract sizes? Can we have two limits, one that requires someone to press an "I understand this will take a while" button and another that we simply refuse to fulfill?

**Comment by heffergm** [comment]
It's very dependant on the area of the world in question and more specifically how much OSM data there is within the region of the extract. I feel that we should just come up with some upper limit and enforce it on the front end.  If you look at the metro extract cities repo, I believe there is a test in there that validates the bbox... one might be for too large.

**Comment by heffergm** [comment]
https://github.com/mapzen/metroextractor-cities/blob/master/spec/bbox_size_spec.rb

**Comment by migurski** [comment]
Thanks Grant, very helpful. Looks like the maximum size is 75° x 75°?

**Comment by heffergm** [comment]
No, that's the region threshold which doesn't apply for odes. The city threshold is 5x5.

**Comment by migurski** [comment]
That’s much more reasonable, thank you. We’ll use it.
