### ISSUE TITLE
Bug: search for africa, tab down, get south africa

### ISSUE THREAD

**Issue by binx** [mapzen/data-pages#66]

**Comment by migurski** [comment]
Select "Africa" from list:

<img width="592" alt="screen shot 2016-06-28 at 4 45 15 pm" src="https://cloud.githubusercontent.com/assets/58730/16436084/c343eb8e-3d4f-11e6-8fc1-b8b6dfc76001.png">

But "South Africa" comes back:

<img width="597" alt="screen shot 2016-06-28 at 4 45 23 pm" src="https://cloud.githubusercontent.com/assets/58730/16436086/c5e6a4d0-3d4f-11e6-9469-2857a604d461.png">
