### ISSUE TITLE
foreign language search works, but fails to create an extract 

### ISSUE THREAD

**Issue by burritojustice** [mapzen/data-pages#96]
Searching for Dhahran, Saudi Arabia doesn't work in English, but does work in Arabic

الظهران

However, this is a point, not a polygon, and creating the request fails.

![image](https://cloud.githubusercontent.com/assets/3979711/16531863/4b9218f0-3f83-11e6-9d16-46a50de985bc.png)

**Comment by binx** [comment]
@burritojustice @migurski the two arabic searches I've done (this one and Cairo) have both returned Point geometry from WOF.

**Comment by migurski** [comment]
We should be able to deal with point geometry; can you make a bbox anyway?

**Comment by binx** [comment]
@migurski and just make it like... 10km radius around the point?

**Comment by migurski** [comment]
Yeah, or maybe a 25x25 since the place itself it probably not a point?
